// Dev-time generator: vendors the app's web fonts locally so the shipped player
// makes ZERO network requests on launch (it previously <link>'d to Google Fonts).
//
// Run once (and again only to refresh/retune the font set):
//   node scripts/fetch-fonts.mjs
//
// It fetches the same css2 the HTML used to request, downloads every woff2 subset
// Google serves (with a desktop-Chrome UA so we get woff2, not ttf), writes them
// to src/assets/fonts/, and emits src/styles/fonts.css with @font-face rules that
// point at those local files. The fonts are OFL/Apache licensed (free to embed).
//
// This script is NOT part of the app bundle — it only produces the committed
// assets. The app itself never runs it and never touches the network for fonts.
import { mkdir, writeFile, rm, readdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const FONTS_DIR = join(ROOT, 'src', 'assets', 'fonts')
const OUT_CSS = join(ROOT, 'src', 'styles', 'fonts.css')

// The exact families/weights the app used from Google Fonts.
const CSS2_URL =
  'https://fonts.googleapis.com/css2?family=Inter:wght@400;500&family=IBM+Plex+Mono:wght@400;500;600&family=Share+Tech+Mono&family=VT323&display=swap'

// A current desktop-Chrome UA — required, or css2 returns ttf instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'

const slug = (s) => s.toLowerCase().replace(/['"]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')

async function main() {
  console.log('Fetching css2…')
  const cssRes = await fetch(CSS2_URL, { headers: { 'User-Agent': UA } })
  if (!cssRes.ok) throw new Error(`css2 fetch failed: ${cssRes.status}`)
  const css = await cssRes.text()

  // Each block is preceded by a `/* subset */` comment.
  const blockRe = /\/\*\s*([^*]+?)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g
  const field = (body, name) => {
    const m = new RegExp(`${name}\\s*:\\s*([^;]+);`).exec(body)
    return m ? m[1].trim() : ''
  }

  await mkdir(FONTS_DIR, { recursive: true })
  // Clear any prior run so removed subsets don't linger.
  for (const f of await readdir(FONTS_DIR).catch(() => [])) {
    if (f.endsWith('.woff2')) await rm(join(FONTS_DIR, f))
  }

  const seen = new Set()
  const cssBlocks = []
  let totalBytes = 0
  let m
  while ((m = blockRe.exec(css)) !== null) {
    const subset = m[1]
    const body = m[2]
    const family = field(body, 'font-family').replace(/['"]/g, '')
    const weight = field(body, 'font-weight') || '400'
    const style = field(body, 'font-style') || 'normal'
    const unicodeRange = field(body, 'unicode-range')
    const urlMatch = /url\((https:\/\/[^)]+\.woff2)\)/.exec(body)
    if (!urlMatch) continue

    const filename = `${slug(family)}-${weight}-${style}-${slug(subset)}.woff2`
    if (seen.has(filename)) continue
    seen.add(filename)

    const fontRes = await fetch(urlMatch[1], { headers: { 'User-Agent': UA } })
    if (!fontRes.ok) throw new Error(`font fetch failed (${filename}): ${fontRes.status}`)
    const buf = Buffer.from(await fontRes.arrayBuffer())
    await writeFile(join(FONTS_DIR, filename), buf)
    totalBytes += buf.length
    console.log(`  ${filename}  (${(buf.length / 1024).toFixed(1)} KB, ${subset})`)

    cssBlocks.push(
      `/* ${family} ${weight} ${style} — ${subset} */\n` +
        `@font-face {\n` +
        `  font-family: '${family}';\n` +
        `  font-style: ${style};\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('../assets/fonts/${filename}') format('woff2');\n` +
        (unicodeRange ? `  unicode-range: ${unicodeRange};\n` : '') +
        `}`
    )
  }

  const header =
    `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.\n` +
    `   Locally-vendored web fonts so the app makes no network requests on launch.\n` +
    `   Fonts: Inter, IBM Plex Mono, Share Tech Mono, VT323 (OFL/Apache). */\n\n`
  await writeFile(OUT_CSS, header + cssBlocks.join('\n\n') + '\n', 'utf-8')

  console.log(`\nWrote ${seen.size} woff2 (${(totalBytes / 1024).toFixed(0)} KB total) + src/styles/fonts.css`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
